version: '3'

services:
  magenode0:
    container_name: magenode0
    image: "mage/magenode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-mage.log}
    volumes:
      - ./build:/mage:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  magenode1:
    container_name: magenode1
    image: "mage/magenode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-mage.log}
    volumes:
      - ./build:/mage:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  magenode2:
    container_name: magenode2
    image: "mage/magenode"
    environment:
      - ID=2
      - LOG=${LOG:-mage.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/mage:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  magenode3:
    container_name: magenode3
    image: "mage/magenode"
    environment:
      - ID=3
      - LOG=${LOG:-mage.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/mage:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
